name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages # Your main development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for gh-pages action

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use the latest LTS version

      - name: Install Dependencies
        run: npm ci

      - name: Build Eleventy
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # The directory Eleventy builds to
          publish_branch: gh-pages # The branch GitHub Pages serves from
          destination_dir: ./ # Deploy to the root of the gh-pages branch
